### ISSUE TITLE
请问一下这个库怎么使用？

### ISSUE THREAD

**Issue by shuaqq2004** [DrAbcOfficial/SilkSharp#1]
C#开发者，想arm（SILK_V3）转mp3或wav格式。
```
Decoder decoder = new();
decoder.decodeAsync("1.amr", "out.pcm");
```
直接decode直接就崩了。 win11.下载了ffmpeg 放在exe同级目录下。

**Comment by DrAbcOfficial** [comment]
该储存库只支持skype silk v3格式，不支持amr格式，请使用ffmpegcore或者其他封装库处理你的问题
ffmpeg相关的问题请去相应储存库提问

**Comment by shuaqq2004** [comment]
是的。我用的是微信的文件 xxx.silk 
使用.NET 8 控制台 想进行转码
```
Decoder decoder = new();
decoder.decodeAsync("1.amr", "out.pcm");   //就这句话 直接就崩了。try catch都无用。
//1.amr 本质是sil的，我只是重命名了一下。
```

**Comment by DrAbcOfficial** [comment]
把你测试的音频上传上来我看看

**Comment by shuaqq2004** [comment]
[wechat.zip](https://github.com/user-attachments/files/17429818/wechat.zip)
附件是 微信的silk文件。 是否需要将微信的silk转成标准的silk？

**Comment by DrAbcOfficial** [comment]
我转换很正常，没有问题
```
using SilkSharp;
Decoder decoder = new();
decoder.Decode("~/桌面/test/bin/Debug/net8.0/1.silk", "~/桌面/test/bin/Debug/net8.0/1.pcm");
```

**Comment by shuaqq2004** [comment]
能否提供一下依赖库呢？ 
silkcodec 我这里是从 https://github.com/foyoux/silk-codec/releases/tag/v1.0.0 页面下载的：silk-decoder-x64.exe
然后重命名成silkcodec就会报错。
是需要自行编译您文件夹里面的silkcodec 吗？

**Comment by DrAbcOfficial** [comment]
> 能否提供一下依赖库呢？ 
> silkcodec 我这里是从 https://github.com/foyoux/silk-codec/releases/tag/v1.0.0 页面下载的：silk-decoder-x64.exe
> 然后重命名成silkcodec就会报错。
> 是需要自行编译您文件夹里面的silkcodec 吗？

1. nuget自带除了Mac之外其他系统的库
2. 不行
3. 如果你是Mac系统，是的

**Comment by DrAbcOfficial** [comment]
> > 能否提供一下依赖库呢？ 
> > silkcodec 我这里是从 https://github.com/foyoux/silk-codec/releases/tag/v1.0.0 页面下载的：silk-decoder-x64.exe
> > 然后重命名成silkcodec就会报错。
> > 是需要自行编译您文件夹里面的silkcodec 吗？
> 
> 1. nuget自带除了Mac之外其他系统的库
> 2. 不行
> 3. 如果你是Mac系统，是的

哦如果你是windows-arm系统，你也需要自己编译，我没有windows-arm这种设备

**Comment by DrAbcOfficial** [comment]
不行你把你的代码贴上来我看看，到底什么问题

**Comment by shuaqq2004** [comment]
我开发是 windows-x64  。 服务器要使用linux-x64
```
SilkSharp.Decoder decoder = new();
decoder.Decode("D:\\1.silk", "D:\\1.pcm");
```
![image](https://github.com/user-attachments/assets/0e4b32cf-cb67-41e5-956f-68fa4834056d)

应该就是依赖库的问题。 我对C不太懂，还不知道怎么编译。

**Comment by DrAbcOfficial** [comment]
你是从nuget拉的依赖么

**Comment by shuaqq2004** [comment]
[SilkTest.zip](https://github.com/user-attachments/files/17539023/SilkTest.zip)
这个是一个demo。
我直接nuget拉的。然后F5运行，没有其他的依赖配置了。裸的。

**Comment by DrAbcOfficial** [comment]
```shell
debian@drabc-pc:~/桌面/1/SilkTest/bin/Debug/net8.0$ dotnet SilkTest.dll
Hello, World!
Unhandled exception. SilkSharp.SilkException.SilkDecoderException: Input file is null
   at SilkSharp.Decoder.Decode(FileInfo slkpath, FileInfo pcmpath)
   at SilkSharp.Decoder.Decode(String slkpath, String pcmpath)
   at Program.<Main>$(String[] args) in C:\Users\Gordo\source\repos\SilkTest\Program.cs:line 6
已放弃 (核心已转储)
```
我直接使用你的二进制文件也没有出现找不到libsilkcodec，要么你检查一下你的runtimes RID是不是有问题，要么你用AOT或者singlefile或者发布到单一平台发布

**Comment by shuaqq2004** [comment]
你这个Input file 为空 ， 是不是还没有执行到 libsilkcodec 的代码去呀。
![image](https://github.com/user-attachments/assets/06b6c494-bb2f-4142-bb7b-0c413923dcfd)
我压缩文件里面包括了 1.silk文件， 你放在d:盘  试试呢。
```
decoder.Decode("D:\\1.silk", "D:\\1.pcm");
```

**Comment by shuaqq2004** [comment]
```
SilkSharp.Decoder decoder = new();
decoder.Decode("1.silk", "1.pcm");
```
我代码改成了相对路径， 并且把1.silk 设定到输出目录了。 
![image](https://github.com/user-attachments/assets/83ab018f-0784-4fba-bb04-19cac0829295)
![image](https://github.com/user-attachments/assets/a898609c-8e18-4e66-8cf2-0ba9baac3fa6)
执行的时候 ，是能生成 1.pcm的文件，同时也报错了。 这个文件 我使用在线pcm 转 wav 后无法播放。
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
```
![image](https://github.com/user-attachments/assets/87098d22-24a3-4f98-b506-471689517efc)
生成的二进制文件有问题 看到基本上都是00或FF

**Comment by DrAbcOfficial** [comment]
2.0.5已修复
