### ISSUE TITLE
2.0.6修改了流，但是转wav播放没有声音

### ISSUE THREAD

**Issue by shuaqq2004** [DrAbcOfficial/SilkSharp#4]
代码同 #3 
不管是通过文件的方式，还是通过流的方式，转成的wav文件 播放无声音！！！ 时长是对的。
我又改回2.0.5了 有声音正常。 先用file的方式save delete 临时再代替一下。

麻烦大神看看什么原因。

**Comment by DrAbcOfficial** [comment]
你先用tempfile吧，因为我不想手搓一个内存流或者引入c++，这个库在windows上的“流”本质上也是通过创建tempfile实现的
等我有时间了再看看什么原因没有写入内存
